name: Bug 反馈
description: 创建一个报告以帮助我们改进
title: "【BUG】"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵时间来反馈问题，这能帮助我们做得更好！
        1. 请务必按照模板提交，不按模板或信息不全的问题将直接关闭。
        2. 在提交前，请先在现有的 issues 中搜索，避免重复提交。
        3. **提交问题务必描述清楚、附上日志**，描述不清导致无法理解和分析的问题会被直接关闭。

  - type: checkboxes
    id: pre-check
    attributes:
      label: 确认事项
      description: 在提交 issue 之前，请确认你已经阅读并完成以下内容。
      options:
        - label: 我已经在此项目的 issues 中搜索过，确认我的问题没有被提出过。
          required: true
        - label: 我已将标题中的默认文字替换为我遇到的具体问题。
          required: true

  - type: dropdown
    id: plugin
    attributes:
      label: 受影响的插件
      description: 请选择您遇到问题的插件。
      options:
        - CCTV探索
        - 咪咕视频探索
        - 哔哩哔哩探索
        - Bangumi每日放送探索
        - 芒果TV探索
        - 腾讯视频探索
        - 115网盘STRM助手
        - 123云盘储存
        - 123云盘STRM助手
        - MediaWarp
        - 神医媒体文件同步删除
        - 其他 (非特定插件问题)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 插件版本号
      description: 请输入您正在使用的插件版本号 (例如：1.0.0)。
      placeholder: "例如：1.0.0"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug 描述
      description: 请清晰简洁地描述这个 Bug 是什么。
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 复现方法
      description: 请提供复现此问题的具体步骤。
      placeholder: |
        1. 前往 '...'
        2. 点击 '....'
        3. 滚动到 '....'
        4. 看到错误

  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: 请将相关的错误日志粘贴到此处。
      render: shell
    validations:
      required: true