name: Rust Build full_sync_strm

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
            target: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.target == 'aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release --out dist
          manylinux: auto
          working-directory: plugins.v2/p115strmhelper/rust_utils/full_strm_sync/

      - name: Build x86_64 musl wheels
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64'
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64-unknown-linux-musl
          command: build
          args: --release --out dist
          manylinux: auto
          working-directory: plugins.v2/p115strmhelper/rust_utils/full_strm_sync/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}
          path: plugins.v2/p115strmhelper/rust_utils/full_strm_sync/dist
